/*
 * AGENT-GENERATED — DO NOT EDIT BY HAND
 * Generated by esp32-sdd-full-project-generator skill
 * Date: 2026-03-10 | Agent: Claude Code
 *
 * BLE Beacon + Deep Sleep — multi-board (ESP32S3, ESP32C6, ESP32C5, ESP32)
 *
 * Stack choice: NimBLE (not Bluedroid). NimBLE initialises in ~50 ms vs ~200 ms
 * for Bluedroid, uses ~30 KB RAM vs ~60 KB, and provides a clean synchronous
 * nimble_port_stop() teardown path — all critical for a duty-cycled beacon
 * followed by immediate deep sleep.
 *
 * Cycle per wake:
 *   1. gpio_hold_dis → determine wakeup cause → increment RTC counters
 *   2. LED on → BLE stack init → start NimBLE host task
 *   3. sync_cb fires → log BLE MAC address → start non-connectable advertising
 *   4. 10 s esp_timer fires → ble_gap_adv_stop → semaphore give
 *   5. app_main unblocks → BLE teardown (5-step) → LED off → gpio_hold_en
 *   6. Configure sleep sources (20 s timer + GPIO button on S3/ESP32) → esp_deep_sleep_start
 *
 * Board-specific configuration is resolved at compile time via Kconfig symbols
 * set in sdkconfig.defaults.<target>. Use `idf.py set-target <target>` to select.
 */

#include <stdint.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

#include "esp_log.h"
#include "esp_sleep.h"
#include "esp_timer.h"
#include "esp_task_wdt.h"
#include "nvs_flash.h"

#include "driver/gpio.h"

#include "nimble/nimble_port.h"
#include "nimble/nimble_port_freertos.h"
#include "host/ble_hs.h"
#include "host/ble_gap.h"

/* -----------------------------------------------------------------------
 * Pin assignments — resolved from sdkconfig.defaults.<target> via Kconfig.
 * Values set in main/Kconfig.projbuild; overridden per target.
 * ----------------------------------------------------------------------- */
#define LED_GPIO        CONFIG_EXAMPLE_LED_GPIO
#define LED_ON          (CONFIG_EXAMPLE_LED_ACTIVE_LEVEL)   /* level that turns LED on  */
#define LED_OFF         (1 - CONFIG_EXAMPLE_LED_ACTIVE_LEVEL) /* level that turns LED off */
#define BUTTON_GPIO     CONFIG_EXAMPLE_BUTTON_GPIO

/* -----------------------------------------------------------------------
 * Timing
 * ----------------------------------------------------------------------- */
#define SLEEP_DURATION_US   (10ULL * 1000000ULL)   /* 10 s deep sleep period */
#define ADV_WINDOW_US       (10000ULL * 1000ULL)    /* 10 s advertising window */

static const char *TAG = "ble_beacon";

/* -----------------------------------------------------------------------
 * RTC-persistent state — survives deep sleep
 * ----------------------------------------------------------------------- */
static RTC_DATA_ATTR uint16_t boot_count = 0;
static RTC_DATA_ATTR uint16_t sequence   = 0;

/* -----------------------------------------------------------------------
 * Module-scope handles — created fresh each wake cycle
 * ----------------------------------------------------------------------- */
static SemaphoreHandle_t  s_adv_done_sem;
static esp_timer_handle_t s_adv_timer;

/* -----------------------------------------------------------------------
 * Forward declarations
 * ----------------------------------------------------------------------- */
static void ble_sync_cb(void);
static void ble_reset_cb(int reason);
static void ble_host_task(void *param);
static void adv_timer_cb(void *arg);
static void start_advertising(void);
static void ble_stack_teardown(void);
static void configure_sleep(void);

/* -----------------------------------------------------------------------
 * Advertising
 *
 * Payload layout (26 bytes total — within the 31-byte PDU limit):
 *   [0x02 0x01 0x06]                     — Flags AD (3 bytes)
 *   [0x0A 0x09 "ESP32-SDD"]              — Complete Local Name AD (11 bytes)
 *   [0x0B 0xFF]                           — Mfr data AD header (2 bytes)
 *   [0xFF 0xFF]                           — Company ID 0xFFFF (2 bytes LE)
 *   [boot_lo boot_hi seq_lo seq_hi]       — boot_count + sequence (4 bytes LE)
 *   [0xDE 0xAD 0xBE 0xEF]                — Magic identifier (4 bytes)
 *
 * The Complete Local Name ("ESP32-SDD") makes the beacon identifiable by name
 * in BLE scanner apps (e.g. nRF Connect) without requiring a MAC address filter.
 * ----------------------------------------------------------------------- */
static void start_advertising(void)
{
    /* Build manufacturer data (company ID + payload, 10 bytes total).
     * NimBLE ble_hs_adv_fields.mfg_data includes the company ID bytes. */
    uint8_t mfg_data[10];
    mfg_data[0] = 0xFF;                        /* Company ID lo (0xFFFF) */
    mfg_data[1] = 0xFF;                        /* Company ID hi */
    mfg_data[2] = (uint8_t)(boot_count);       /* boot_count lo */
    mfg_data[3] = (uint8_t)(boot_count >> 8);  /* boot_count hi */
    mfg_data[4] = (uint8_t)(sequence);         /* sequence lo */
    mfg_data[5] = (uint8_t)(sequence >> 8);    /* sequence hi */
    mfg_data[6] = 0xDE;
    mfg_data[7] = 0xAD;
    mfg_data[8] = 0xBE;
    mfg_data[9] = 0xEF;

    struct ble_hs_adv_fields fields = {0};
    /* 0x06 = LE General Discoverable | BR/EDR Not Supported */
    fields.flags             = BLE_HS_ADV_F_DISC_GEN | BLE_HS_ADV_F_BREDR_UNSUP;
    /* Complete Local Name — shown in BLE scanner app device lists by name */
    fields.name              = (uint8_t *)"ESP32-SDD";
    fields.name_len          = 9;
    fields.name_is_complete  = 1;
    fields.mfg_data          = mfg_data;
    fields.mfg_data_len      = sizeof(mfg_data);

    int rc = ble_gap_adv_set_fields(&fields);
    if (rc != 0) {
        ESP_LOGE(TAG, "adv_set_fields failed rc=%d — proceeding to sleep", rc);
        xSemaphoreGive(s_adv_done_sem);
        return;
    }

    /* Non-connectable, non-discoverable advertising at 100 ms interval.
     * itvl = desired_ms / 0.625: 100 ms / 0.625 = 160 units */
    struct ble_gap_adv_params adv_params = {0};
    adv_params.conn_mode = BLE_GAP_CONN_MODE_NON;
    adv_params.disc_mode = BLE_GAP_DISC_MODE_NON;
    adv_params.itvl_min  = 160;
    adv_params.itvl_max  = 160;

    /* BLE_HS_FOREVER: no built-in timeout — our 10 s esp_timer controls the window */
    rc = ble_gap_adv_start(BLE_OWN_ADDR_PUBLIC, NULL, BLE_HS_FOREVER,
                           &adv_params, NULL, NULL);
    if (rc != 0) {
        ESP_LOGE(TAG, "adv_start failed rc=%d — proceeding to sleep", rc);
        xSemaphoreGive(s_adv_done_sem);
        return;
    }

    ESP_LOGI(TAG, "Advertising: name=ESP32-SDD boot_count=%u seq=%u mfg=[FF FF %02X %02X %02X %02X DE AD BE EF]",
             boot_count, sequence,
             mfg_data[2], mfg_data[3], mfg_data[4], mfg_data[5]);
}

/* Called by NimBLE host task when host and controller are synchronised.
 * This is the correct entry point for logging the MAC and starting advertising. */
static void ble_sync_cb(void)
{
    /* Log the BLE public address so the user can find this device in a scanner app.
     * NimBLE stores addresses in little-endian byte order; print MSB-first for display. */
    uint8_t addr_val[6] = {0};
    int rc = ble_hs_id_copy_addr(BLE_ADDR_PUBLIC, addr_val, NULL);
    if (rc == 0) {
        ESP_LOGI(TAG, "BLE MAC: %02X:%02X:%02X:%02X:%02X:%02X",
                 addr_val[5], addr_val[4], addr_val[3],
                 addr_val[2], addr_val[1], addr_val[0]);
    } else {
        ESP_LOGW(TAG, "BLE MAC: read failed (rc=%d)", rc);
    }

    start_advertising();
}

/* Called if the NimBLE host resets unexpectedly (e.g. controller crash).
 * Per CodingSpec: log and proceed to sleep rather than blocking. */
static void ble_reset_cb(int reason)
{
    ESP_LOGE(TAG, "NimBLE host reset reason=%d — proceeding to sleep", reason);
    xSemaphoreGive(s_adv_done_sem);
}

/* NimBLE host task entry point.
 * nimble_port_run() blocks until nimble_port_stop() signals it to exit. */
static void ble_host_task(void *param)
{
    nimble_port_run();
    nimble_port_freertos_deinit();
}

/* -----------------------------------------------------------------------
 * Advertising window timer callback
 *
 * esp_timer callbacks run in a dedicated FreeRTOS task — safe to call
 * NimBLE API and FreeRTOS primitives (not an ISR context).
 * ----------------------------------------------------------------------- */
static void adv_timer_cb(void *arg)
{
    ble_gap_adv_stop();
    xSemaphoreGive(s_adv_done_sem);
}

/* -----------------------------------------------------------------------
 * BLE stack teardown — MUST complete before esp_deep_sleep_start()
 *
 * Order is critical (see shared-specs/ble-patterns.md):
 *   nimble_port_stop() posts an event to the host task and BLOCKS until
 *   the task exits. Calling esp_bt_controller_disable() before the host
 *   task exits causes an assertion in the controller.
 * ----------------------------------------------------------------------- */
static void ble_stack_teardown(void)
{
    ble_gap_adv_stop();     /* idempotent — safe if already stopped by timer */

    int rc = nimble_port_stop();
    if (rc != 0) {
        ESP_LOGE(TAG, "nimble_port_stop rc=%d", rc);
    }

    nimble_port_deinit();

    ESP_LOGI(TAG, "BLE stack torn down");
}

/* -----------------------------------------------------------------------
 * Deep sleep wakeup source configuration
 *
 * Original ESP32 supports ext0 (single GPIO, any edge). RTC GPIOs: 0,2,4,12-15,25-27,32-39.
 * ESP32-S3: use ext1; GPIO 0-21 are all RTC-capable.
 * ESP32-C6: only GPIO 0-7 are RTC GPIOs. The XIAO boot button (GPIO 9) is NOT RTC-capable.
 * ESP32-C5: only GPIO 0-6 are RTC GPIOs. The XIAO boot button (GPIO 9) is NOT RTC-capable.
 * On C6/C5 we fall back to timer-only wakeup — no external hardware required.
 * ----------------------------------------------------------------------- */
static void configure_sleep(void)
{
    /* RTC timer: wake after 10 seconds (all targets) */
    ESP_ERROR_CHECK(esp_sleep_enable_timer_wakeup(SLEEP_DURATION_US));

#if CONFIG_IDF_TARGET_ESP32
    /* Original ESP32: ext0 supported; GPIO 0 = RTCIO_CHANNEL_11. */
    gpio_pullup_en(BUTTON_GPIO);
    gpio_pulldown_dis(BUTTON_GPIO);
    ESP_ERROR_CHECK(esp_sleep_enable_ext0_wakeup(BUTTON_GPIO, 0));
#elif CONFIG_IDF_TARGET_ESP32S3
    /* ESP32-S3: GPIO 0-21 are all RTC GPIOs; use ext1 with single-GPIO bitmask. */
    gpio_pullup_en(BUTTON_GPIO);
    gpio_pulldown_dis(BUTTON_GPIO);
    ESP_ERROR_CHECK(esp_sleep_enable_ext1_wakeup(1ULL << BUTTON_GPIO, ESP_EXT1_WAKEUP_ANY_LOW));
#else
    /* ESP32-C6: only GPIO 0-7 are LP/RTC GPIOs — boot button (GPIO 9) is not RTC-capable.
     * ESP32-C5: only GPIO 0-6 are LP/RTC GPIOs — boot button (GPIO 9) is not RTC-capable.
     * Timer-only wakeup; no ext wakeup source configured on these targets. */
    ESP_LOGI(TAG, "Button wakeup not available: boot button GPIO not RTC-capable on this target");
#endif
}

/* -----------------------------------------------------------------------
 * app_main — runs once per wake cycle, then enters deep sleep
 * ----------------------------------------------------------------------- */
void app_main(void)
{
    /* Subscribe to task watchdog for this single-pass execution */
    esp_task_wdt_add(NULL);
    esp_task_wdt_reset();

    /* Release GPIO hold from the previous sleep cycle before driving any pin.
     * gpio_hold_dis() is a no-op on first boot — safe to call unconditionally. */
    gpio_hold_dis(LED_GPIO);

    /* ---- Wakeup cause ---- */
    esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
    switch (cause) {
        case ESP_SLEEP_WAKEUP_TIMER:
            ESP_LOGI(TAG, "Wakeup: TIMER");
            break;
#if CONFIG_IDF_TARGET_ESP32
        case ESP_SLEEP_WAKEUP_EXT0:
            ESP_LOGI(TAG, "Wakeup: EXT0 (button press)");
            break;
#elif CONFIG_IDF_TARGET_ESP32S3
        case ESP_SLEEP_WAKEUP_EXT1:
            ESP_LOGI(TAG, "Wakeup: EXT1 (button press)");
            break;
#endif
        default:
            ESP_LOGI(TAG, "Wakeup: FIRST_BOOT or RESET (%d)", (int)cause);
            break;
    }

    /* ---- Increment RTC-persistent counters ---- */
    boot_count++;
    sequence++;
    ESP_LOGI(TAG, "Cycle: boot_count=%u seq=%u", boot_count, sequence);
    esp_task_wdt_reset();

    /* ---- LED on ---- */
    gpio_config_t led_cfg = {
        .pin_bit_mask = (1ULL << LED_GPIO),
        .mode         = GPIO_MODE_OUTPUT,
        .pull_up_en   = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE,
    };
    ESP_ERROR_CHECK(gpio_config(&led_cfg));
    gpio_set_level(LED_GPIO, LED_ON);

    /* ---- Create synchronisation semaphore ---- */
    s_adv_done_sem = xSemaphoreCreateBinary();
    configASSERT(s_adv_done_sem != NULL);

    /* ---- NVS init — required by BLE controller for PHY calibration data ---- */
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    /* ---- Initialise NimBLE (controller + host) ---- */
    ESP_ERROR_CHECK(nimble_port_init());

    ble_hs_cfg.sync_cb  = ble_sync_cb;
    ble_hs_cfg.reset_cb = ble_reset_cb;

    /* Start NimBLE host task; sync_cb fires once host/controller are ready */
    nimble_port_freertos_init(ble_host_task);

    /* ---- Start 10 s advertising window timer ---- */
    esp_timer_create_args_t timer_args = {
        .callback = adv_timer_cb,
        .name     = "adv_window",
    };
    ESP_ERROR_CHECK(esp_timer_create(&timer_args, &s_adv_timer));
    ESP_ERROR_CHECK(esp_timer_start_once(s_adv_timer, ADV_WINDOW_US));

    /* Unsubscribe from task WDT before the 10 s blocking wait — default timeout is 5 s */
    esp_task_wdt_delete(NULL);

    /* ---- Block until advertising window expires (or adv fails) ---- */
    xSemaphoreTake(s_adv_done_sem, portMAX_DELAY);

    /* Re-subscribe for the teardown phase */
    esp_task_wdt_add(NULL);
    esp_task_wdt_reset();

    /* Clean up timer — one-shot may already be expired (ESP_ERR_INVALID_STATE is OK) */
    esp_timer_stop(s_adv_timer);
    esp_timer_delete(s_adv_timer);
    vSemaphoreDelete(s_adv_done_sem);

    /* ---- Full BLE teardown — leaving radio powered destroys the power budget ---- */
    ble_stack_teardown();
    esp_task_wdt_reset();

    /* ---- LED off, hold GPIO state across deep sleep ---- */
    gpio_set_level(LED_GPIO, LED_OFF);
    gpio_hold_en(LED_GPIO);

    /* ---- Configure wakeup sources ---- */
    configure_sleep();

    ESP_LOGI(TAG, "Entering deep sleep (10 s). Active window complete.");

    /* Unsubscribe from watchdog before sleeping — required for deep-sleep examples */
    esp_task_wdt_delete(NULL);

    esp_deep_sleep_start();
}
